(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(anzu-deactivate-region t)
 '(anzu-mode-lighter " Az ")
 '(anzu-mode-line-update-function #'my/anzu-update-func)
 '(anzu-replace-threshold 50)
 '(anzu-replace-to-string-separator " => ")
 '(anzu-search-threshold 1000)
 '(helm-ff-lynx-style-map t)
 '(helm-grep-use-ioccur-style-keys t)
 '(helm-imenu-lynx-style-map t)
 '(helm-occur-use-ioccur-style-keys t)
 '(helm-semantic-lynx-style-map t)
 '(package-selected-packages
   '(company-jedi jedi-company yasnippet xterm-color winnow which-key wgrep-helm wgrep-ag web-mode volatile-highlights visual-regexp-steroids vimish-fold use-package-hydra tree-sitter-langs syslog-mode swiper-helm smartparens smart-mode-line quelpa-use-package powerline phi-grep pfuture peep-dired page-break-lines org-modern occur-x multiple-cursors move-lines markdown-mode major-mode-hydra magit loccur interaction-log iedit ido-vertical-mode ido-completing-read+ htmlize ht highlight-symbol highlight-parentheses highlight helpful help-fns+ helm-swoop helm-ls-git helm-helm-commands helm-describe-modes helm-descbinds helm-company helm-backup helm-ag gitignore-mode gitconfig-mode gitattributes-mode gcmh free-keys frame-local flycheck flx-ido emmet-mode elmacro duplicate-thing doom-modeline diredfl dired-subtree dired-quick-sort dired-narrow diminish dash-functional counsel company-shell company-flx cfrs benchmark-init bash-completion backup-each-save anzu amx all-the-icons-ivy all-the-icons-dired ag ace-window)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((((class color) (min-colors 89)) (:inherit nil :stipple nil :inverse-vidppeo nil :box nil :strike-through nil :overline nil :underline nil :foreground "#c5c9d1" :distant-foreground "orange" :background "#002b36" :height 120 :slant normal :weight normal :width normal))))
 '(Info-title-1-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(Info-title-2-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))))
 '(Info-title-3-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF"))))
 '(Info-title-4-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#EA6300"))))
 '(ac-completion-face ((((class color) (min-colors 89)) (:underline nil :foreground "#C0C0C0"))))
 '(ace-jump-face-foreground ((((class color) (min-colors 89)) (:foreground "black" :background "#FBE448"))))
 '(auto-dim-other-buffers-face ((((class color) (min-colors 89)) (:background "#F7F7F7"))))
 '(bbdb-company ((((class color) (min-colors 89)) (:slant italic :foreground "steel blue"))))
 '(bbdb-field-name ((((class color) (min-colors 89)) (:weight bold :foreground "steel blue"))))
 '(bbdb-field-value ((((class color) (min-colors 89)) (:foreground "steel blue"))))
 '(bbdb-name ((((class color) (min-colors 89)) (:underline t :foreground "#FF6633"))))
 '(bmkp-light-autonamed ((((class color) (min-colors 89)) (:background "#C2DDFD"))))
 '(bmkp-light-fringe-autonamed ((((class color) (min-colors 89)) (:background "#90AFD5"))))
 '(bmkp-light-fringe-non-autonamed ((((class color) (min-colors 89)) (:background "#D5FFD5"))))
 '(bmkp-light-non-autonamed ((((class color) (min-colors 89)) (:background "#C4FFC4"))))
 '(bold ((((class color) (min-colors 89)) (:weight bold :foreground "black"))))
 '(bold-italic ((((class color) (min-colors 89)) (:weight bold :slant italic :foreground "black"))))
 '(browse-kill-ring-separator-face ((((class color) (min-colors 89)) (:weight bold :foreground "slate gray"))))
 '(button ((((class color) (min-colors 89)) (:underline t :foreground "#006DAF"))))
 '(calendar-today ((((class color) (min-colors 89)) (:weight bold :foreground "#4F4A3D" :background "#FFFFCC"))))
 '(cfw:face-annotation ((((class color) (min-colors 89)) (:foreground "green" :background "red"))))
 '(cfw:face-day-title ((((class color) (min-colors 89)) (:foreground "#C9C9C9"))))
 '(cfw:face-default-content ((((class color) (min-colors 89)) (:foreground "#2952A3"))))
 '(cfw:face-default-day ((((class color) (min-colors 89)) (:weight bold))))
 '(cfw:face-disable ((((class color) (min-colors 89)) (:foreground "DarkGray"))))
 '(cfw:face-grid ((((class color) (min-colors 89)) (:foreground "#DDDDDD"))))
 '(cfw:face-header ((((class color) (min-colors 89)) (:foreground "#1662AF" :background "white" :weight bold))))
 '(cfw:face-holiday ((((class color) (min-colors 89)) (:foreground "#777777" :background "#E4EBFE"))))
 '(cfw:face-periods ((((class color) (min-colors 89)) (:foreground "white" :background "#668CD9" :slant italic))))
 '(cfw:face-saturday ((((class color) (min-colors 89)) (:foreground "#4E4E4E" :background "white" :weight bold))))
 '(cfw:face-select ((((class color) (min-colors 89)) (:foreground "#4A95EB" :background "#EDF1FA"))))
 '(cfw:face-sunday ((((class color) (min-colors 89)) (:foreground "#4E4E4E" :background "white" :weight bold))))
 '(cfw:face-title ((((class color) (min-colors 89)) (:height 2.0 :foreground "#676767" :weight bold :inherit variable-pitch))))
 '(cfw:face-today ((((class color) (min-colors 89)) (:foreground "#4F4A3D" :background "#FFFFCC"))))
 '(cfw:face-today-title ((((class color) (min-colors 89)) (:foreground "#4A95EB" :background "#FFFFCC"))))
 '(cfw:face-toolbar ((((class color) (min-colors 89)) (:background "white"))))
 '(cfw:face-toolbar-button-off ((((class color) (min-colors 89)) (:foreground "#CFCFCF" :background "white"))))
 '(cfw:face-toolbar-button-on ((((class color) (min-colors 89)) (:foreground "#5E5E5E" :background "#F6F6F6"))))
 '(change-log-date-face ((((class color) (min-colors 89)) (:foreground "purple"))))
 '(change-log-file ((((class color) (min-colors 89)) (:weight bold :foreground "#4183C4"))))
 '(circe-highlight-all-nicks-face ((((class color) (min-colors 89)) (:foreground "blue" :background "#F0F0F0"))))
 '(circe-highlight-nick-face ((((class color) (min-colors 89)) (:foreground "#009300" :background "#F0F0F0"))))
 '(circe-my-message-face ((((class color) (min-colors 89)) (:foreground "#8B8B8B" :background "#F0F0F0"))))
 '(circe-originator-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(circe-prompt-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(circe-server-face ((((class color) (min-colors 89)) (:foreground "#99CAE5"))))
 '(comint-highlight-input ((((class color) (min-colors 89)) (:weight bold :foreground "#0000FF" :inherit nil))))
 '(comint-highlight-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "#0000FF" :inherit nil))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#C0C0C0" :background "#FFFFD7"))))
 '(company-preview-search ((t (:inherit company-preview :background "black"))))
 '(company-template-field ((t (:background "black" :foreground "chartreuse"))))
 '(company-tooltip ((t (:background "black" :foreground "yellow green"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:foreground "#999999" :background "cornsilk"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:weight bold :inherit company-tooltip))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:weight bold :inherit company-tooltip-selection))))
 '(company-tooltip-scrollbar-thumb ((t (:background "red"))))
 '(company-tooltip-scrollbar-track ((t (:background "dark green"))))
 '(company-tooltip-search ((t (:foreground "dark khaki" :underline "blue"))))
 '(company-tooltip-selection ((t (:background "honeydew" :foreground "dark green"))))
 '(compare-windows ((((class color) (min-colors 89)) (:background "#FFFF00"))))
 '(compilation-error ((((class color) (min-colors 89)) (:weight bold :foreground "red"))))
 '(compilation-info ((((class color) (min-colors 89)) (:weight bold :foreground "#2A489E"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:weight bold :foreground "#A535AE"))))
 '(compilation-warning ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(css-property ((((class color) (min-colors 89)) (:foreground "#00AA00"))))
 '(css-selector ((((class color) (min-colors 89)) (:weight bold :foreground "blue"))))
 '(cursor ((((class color) (min-colors 89)) (:background "#ced23a"))))
 '(custom-button ((((class color) (min-colors 89)) (:box (:line-width 2 :style released-button) :foreground "black" :background "lightgrey"))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:box (:line-width 2 :style released-button) :foreground "black" :background "grey90"))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:box (:line-width 2 :style pressed-button) :foreground "black" :background "light grey"))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 89)) (:underline t :foreground "magenta4"))))
 '(custom-button-unraised ((((class color) (min-colors 89)) (:underline t))))
 '(custom-changed ((((class color) (min-colors 89)) (:foreground "white" :background "blue"))))
 '(custom-comment ((((class color) (min-colors 89)) (:background "gray85"))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "blue4"))))
 '(custom-documentation ((((class color) (min-colors 89)) (nil))))
 '(custom-face-tag ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:height 1.2 :weight bold :foreground "blue1"))))
 '(custom-group-tag-1 ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold :foreground "red1"))))
 '(custom-invalid ((((class color) (min-colors 89)) (:foreground "yellow" :background "red"))))
 '(custom-link ((((class color) (min-colors 89)) (:underline t :foreground "blue1"))))
 '(custom-modified ((((class color) (min-colors 89)) (:foreground "white" :background "blue"))))
 '(custom-rogue ((((class color) (min-colors 89)) (:foreground "pink" :background "black"))))
 '(custom-saved ((((class color) (min-colors 89)) (:underline t))))
 '(custom-set ((((class color) (min-colors 89)) (:foreground "blue" :background "white"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(custom-themed ((((class color) (min-colors 89)) (:foreground "white" :background "blue1"))))
 '(custom-variable-button ((((class color) (min-colors 89)) (:weight bold :underline t))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold :foreground "blue1"))))
 '(custom-visibility ((((class color) (min-colors 89)) (:weight normal :foreground "#04cca7"))))
 '(diary-face ((((class color) (min-colors 89)) (:foreground "#87C9FC"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#008000" :background "#DDFFDD"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#0000FF" :background "#DDDDFF"))))
 '(diff-context ((((class color) (min-colors 89)) (:foreground "gray33"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#800000" :background "#FFFFAF"))))
 '(diff-file1-hunk-header ((((class color) (min-colors 89)) (:foreground "dark magenta" :background "#EAF2F5"))))
 '(diff-file2-hunk-header ((((class color) (min-colors 89)) (:foreground "#2B7E2A" :background "#EAF2F5"))))
 '(diff-function ((((class color) (min-colors 89)) (:foreground "darkgray"))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#800000" :background "#FFFFAF"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:foreground "blue3" :inherit diff-changed))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:foreground "red3" :inherit diff-removed))))
 '(diff-hl-dired-change ((((class color) (min-colors 89)) (:background "#FFA335" :foreground "black" :weight bold))))
 '(diff-hl-dired-unknown ((((class color) (min-colors 89)) (:foreground "white" :background "#3F3BB4"))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:foreground "green4" :inherit diff-added))))
 '(diff-hl-unknown ((((class color) (min-colors 89)) (:foreground "white" :background "#3F3BB4"))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#990099" :background "#FFEEFF"))))
 '(diff-index ((((class color) (min-colors 89)) (:foreground "#800000" :background "#FFFFAF"))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:background "#AAFFAA"))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:background "#8080FF"))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:background "#FFBBBB"))))
 '(diff-refine-change ((((class color) (min-colors 89)) (:background "#DDDDFF"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#A60000" :background "#FFDDDD"))))
 '(dircolors-face-asm ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-backup ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-compress ((((class color) (min-colors 89)) (:foreground "red"))))
 '(dircolors-face-dir ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(dircolors-face-doc ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-dos ((((class color) (min-colors 89)) (:foreground "ForestGreen"))))
 '(dircolors-face-emacs ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-exec ((((class color) (min-colors 89)) (:foreground "ForestGreen"))))
 '(dircolors-face-html ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-img ((((class color) (min-colors 89)) (:foreground "magenta3"))))
 '(dircolors-face-lang ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-lang-interface ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-make ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-objet ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-package ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-paddb ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-ps ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-sound ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue"))))
 '(dircolors-face-tar ((((class color) (min-colors 89)) (:foreground "red"))))
 '(dircolors-face-text ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-yacc ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dired-directory ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(dired-header ((((class color) (min-colors 89)) (:background "#03C03C" :foreground "red"))))
 '(dired-ignored ((((class color) (min-colors 89)) (:strike-through t :foreground "red"))))
 '(dired-mark ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "red"))))
 '(dired-marked ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "red"))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "deep sky blue"))))
 '(diredp-compressed-file-suffix ((((class color) (min-colors 89)) (:foreground "red"))))
 '(diredp-date-time ((((class color) (min-colors 89)) (:foreground "purple"))))
 '(diredp-dir-heading ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(diredp-dir-priv ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(diredp-exec-priv ((((class color) (min-colors 89)) (:background "#03C03C"))))
 '(diredp-executable-tag ((((class color) (min-colors 89)) (:foreground "ForestGreen" :background "white"))))
 '(diredp-file-name ((((class color) (min-colors 89)) (:foreground "black"))))
 '(diredp-file-suffix ((((class color) (min-colors 89)) (:foreground "#C0C0C0"))))
 '(diredp-flag-mark-line ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "red"))))
 '(diredp-ignored-file-name ((((class color) (min-colors 89)) (:foreground "#7F7F7F"))))
 '(diredp-read-priv ((((class color) (min-colors 89)) (:background "#0A99FF"))))
 '(diredp-write-priv ((((class color) (min-colors 89)) (:foreground "white" :background "#FF4040"))))
 '(ediff-current-diff-A ((((class color) (min-colors 89)) (:foreground "gray33" :background "#FFDDDD"))))
 '(ediff-current-diff-B ((((class color) (min-colors 89)) (:foreground "gray33" :background "#DDFFDD"))))
 '(ediff-current-diff-C ((((class color) (min-colors 89)) (:foreground "black" :background "cyan"))))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:foreground "black" :background "light grey"))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:foreground "black" :background "light grey"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 89)) (:foreground "#A60000" :background "#FFAAAA"))))
 '(ediff-fine-diff-B ((((class color) (min-colors 89)) (:foreground "#008000" :background "#55FF55"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:foreground "black" :background "light grey"))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:foreground "black" :background "light grey"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#008ED1"))))
 '(file-name-shadow ((((class color) (min-colors 89)) (:foreground "#7F7F7F"))))
 '(font-latex-bold-face ((((class color) (min-colors 89)) (:weight bold :foreground "black"))))
 '(font-latex-italic-face ((((class color) (min-colors 89)) (:slant italic :foreground "#1A1A1A"))))
 '(font-latex-math-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(font-latex-sectioning-1-face ((((class color) (min-colors 89)) (:family "Sans Serif" :height 2.7 :weight bold :foreground "cornflower blue"))))
 '(font-latex-sectioning-2-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(font-latex-sectioning-3-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))))
 '(font-latex-sectioning-4-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF"))))
 '(font-latex-sectioning-5-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#EA6300"))))
 '(font-latex-sedate-face ((((class color) (min-colors 89)) (:foreground "#FF5500"))))
 '(font-latex-string-face ((((class color) (min-colors 89)) (:weight bold :foreground "#0066FF"))))
 '(font-latex-verbatim-face ((((class color) (min-colors 89)) (:foreground "#000088" :background "#FFFFE0" :inherit nil))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#5e5c5c"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:slant italic :foreground "#5e5c5c"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#D0372D"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#036A07"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:weight normal :foreground "#006699"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold nil :foreground "#2aa198"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#808080"))))
 '(font-lock-reference-face ((((class color) (min-colors 89)) (bold t :foreground "MediumPurple"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold :inherit nil))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold :inherit nil))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#05a805"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:weight normal :foreground "#7d42c9"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:weight normal :foreground "#858503"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:bold t :weight bold :foreground "red"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#9B9B9B" :background "#EDEDED"))))
 '(git-commit-comment-face ((((class color) (min-colors 89)) (:slant italic :foreground "#696969"))))
 '(git-commit-summary-face ((((class color) (min-colors 89)) (:foreground "#000000"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :weight bold :underline "black" :overline "black" :box nil :background "#073642" :foreground "#93a1a1"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "LimeGreen"))))
 '(helm-buffer-file ((((class color) (min-colors 89)) (:foreground "White"))))
 '(helm-ff-denied ((((class color) (min-colors 89)) (:foreground "red" :background nil :weight bold))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "LimeGreen"))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) (:foreground "LimeGreen"))))
 '(helm-ff-dotted-symlink-directory ((((class color) (min-colors 89)) (:foreground "#8b0000"))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "gray75" :background nil))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:foreground "black" :background "red"))))
 '(helm-ff-prefix ((((class color) (min-colors 89)) (:foreground "red" :background nil :weight bold))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "blue" :background "DarkOliveGreen"))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:foreground "#511a1a"))))
 '(helm-match ((((class color) (min-colors 89)) (:foreground "#511a1a"))))
 '(helm-match-item ((((class color) (min-colors 89)) (:foreground "#511a1a" :weight bold))))
 '(helm-non-file-buffer ((((class color) (min-colors 89)) (:foreground "red"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#575757" :weight bold))))
 '(helm-source-header ((((class color) (min-colors 89)) (:foreground "white" :background "#511a1a" :weight bold :height 150))))
 '(helm-swoop-line-number-face ((((class color) (min-colors 89)) (:foreground "GreenYellow"))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:foreground "black" :background "goldenrod"))))
 '(highlight ((((class color) (min-colors 89)) (:underline nil :background "#586e75" :foreground "#002b36"))))
 '(highlight-parentheses-highlight ((t (:weight bold :height 1.0 :background "#1d2014"))) t)
 '(highlight-symbol-face ((((class color) (min-colors 89)) (:background "#FFFFA0"))))
 '(hl-line ((((class color) (min-colors 89)) (:inherit t :background "#3d4753" :foreground nil))))
 '(hl-tags-face ((((class color) (min-colors 89)) (:background "#FEFCAE"))))
 '(holiday-face ((((class color) (min-colors 89)) (:foreground "#777777" :background "#E4EBFE"))))
 '(homoglyph ((((class color) (min-colors 89)) (:foreground "#008ED1"))))
 '(html-helper-bold-face ((((class color) (min-colors 89)) (:weight bold :foreground "black"))))
 '(html-helper-italic-face ((((class color) (min-colors 89)) (:slant italic :foreground "black"))))
 '(html-helper-underline-face ((((class color) (min-colors 89)) (:underline t :foreground "black"))))
 '(html-tag-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(ilog-change-face ((((class color) (min-colors 89)) (:height 1.0 :foreground "#008200"))))
 '(ilog-echo-face ((((class color) (min-colors 89)) (:height 1.0 :foreground "#006FE0"))))
 '(ilog-load-face ((((class color) (min-colors 89)) (:foreground "#BA36A5"))))
 '(ilog-message-face ((((class color) (min-colors 89)) (:foreground "#808080"))))
 '(ilog-non-change-face ((((class color) (min-colors 89)) (:height 1.0 :foreground "#6434A3"))))
 '(info-file ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.0 :weight bold :box (:line-width 1 :color "#0000CC") :foreground "cornflower blue" :background "LightSteelBlue1"))))
 '(info-header-node ((((class color) (min-colors 89)) (:underline t :foreground "orange"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:underline t :foreground "dodger blue"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))))
 '(info-menu-star ((((class color) (min-colors 89)) (:foreground "black"))))
 '(info-node ((((class color) (min-colors 89)) (:underline t :foreground "blue"))))
 '(info-quoted-name ((((class color) (min-colors 89)) (:foreground "#006400" :background "#FDFFF7"))))
 '(info-string ((((class color) (min-colors 89)) (:foreground "#05a805"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(info-xref ((((class color) (min-colors 89)) (:underline t :foreground "#006DAF"))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:underline t :foreground "magenta4"))))
 '(isearch ((((class color) (min-colors 89)) (:weight bold :underline "#FF9632" :foreground "#eeeeec" :background "#ce5c00"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#FF9999"))))
 '(italic ((((class color) (min-colors 89)) (:slant italic :foreground "#1A1A1A"))))
 '(ivy-modified-buffer ((t (:inherit default :weight bold :foreground "#FD971F"))))
 '(ivy-modified-outside-buffer ((t (:foreground "red" :weight bold))))
 '(ivy-virtual ((t (:inherit default :foreground "green"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:underline "#FF9632" :background "#FFFF00"))))
 '(light-symbol-face ((((class color) (min-colors 89)) (:background "#FFFFA0"))))
 '(link ((((class color) (min-colors 89)) (:weight normal :foreground "#04cca7"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#E5786D"))))
 '(linkd-generic-link ((((class color) (min-colors 89)) (:foreground "yellow" :underline t))))
 '(linkd-generic-link-name ((((class color) (min-colors 89)) (:foreground "yellow" :underline t))))
 '(linkd-tag ((((class color) (min-colors 89)) (:foreground "white" :underline t))))
 '(linkd-tag-name ((((class color) (min-colors 89)) (:foreground "white" :underline t))))
 '(linum ((((class color) (min-colors 89)) (:inherit (default shadow) :foreground "#9A9A9A" :background "#242323"))))
 '(log-view-file ((((class color) (min-colors 89)) (:foreground "#0000CC" :background "#EAF2F5"))))
 '(lui-button-face ((((class color) (min-colors 89)) (:weight normal :foreground "#04cca7"))))
 '(lui-highlight-face ((((class color) (min-colors 89)) (:box '(:line-width 1 :color "#CC0000") :foreground "#CC0000" :background "#FFFF88"))))
 '(lui-time-stamp-face ((((class color) (min-colors 89)) (:foreground "purple"))))
 '(magit-branch ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#00CC33") :foreground "black" :background "#AAFFAA"))))
 '(magit-diff-add ((((class color) (min-colors 89)) (:foreground "#008000" :background "#DDFFDD"))))
 '(magit-diff-del ((((class color) (min-colors 89)) (:foreground "#A60000" :background "#FFDDDD"))))
 '(magit-diff-file-header ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.1 :weight bold :foreground "#4183C4"))))
 '(magit-diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#990099" :background "#FFEEFF"))))
 '(magit-diff-none ((((class color) (min-colors 89)) (:foreground "gray33"))))
 '(magit-header ((((class color) (min-colors 89)) (:foreground "white" :background "#FF4040"))))
 '(magit-item-highlight ((((class color) (min-colors 89)) (:background "#EAF2F5"))))
 '(magit-item-mark ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "red"))))
 '(magit-log-head-label ((((class color) (min-colors 89)) (:box (:line-width 1 :color "blue" :style nil)))))
 '(magit-log-tag-label ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#00CC00" :style nil)))))
 '(magit-section-title ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.8 :weight bold :foreground "cornflower blue" :inherit nil))))
 '(makefile-space-face ((((class color) (min-colors 89)) (:background "hot pink"))))
 '(makefile-targets ((((class color) (min-colors 89)) (:weight bold :foreground "blue"))))
 '(match ((((class color) (min-colors 89)) (:weight bold :background "#1f1f1f"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#5050B0"))) t)
 '(message-header-cc ((((class color) (min-colors 89)) (:family "Sans Serif" :underline nil :foreground "#006DAF"))))
 '(message-header-name ((((class color) (min-colors 89)) (:family "Sans Serif" :weight normal :foreground "#A3A3A2"))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:family "Sans Serif" :foreground "#3399CC"))))
 '(message-header-other ((((class color) (min-colors 89)) (:family "Sans Serif" :slant normal :foreground "#666666"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:family "Sans Serif" :weight bold :foreground "black"))))
 '(message-header-to ((((class color) (min-colors 89)) (:family "Sans Serif" :underline nil :foreground "#006DAF"))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:family "Sans Serif" :slant normal :foreground "#666666"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "forest green"))))
 '(message-separator ((((class color) (min-colors 89)) (:family "Sans Serif" :weight normal :foreground "#BDC2C6"))))
 '(minibuffer-noticeable-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "gold"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "#FFFF00"))))
 '(mm-uu-extract ((((class color) (min-colors 89)) (:foreground "#000088" :background "#FFFFE0"))))
 '(moccur-current-line-face ((((class color) (min-colors 89)) (:foreground "black" :background "#FFFFCC"))))
 '(moccur-face ((((class color) (min-colors 89)) (:foreground "black" :background "#FFFF99"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#1A2F54") :foreground "#85CEEB" :background "#335EA8"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :foreground "white"))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:weight bold :foreground "white"))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "yellow"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#4E4E4C") :foreground "#F0F0EF" :background "#9B9C97"))))
 '(next-error ((((class color) (min-colors 89)) (:underline nil :background "#586e75" :foreground "#002b36"))))
 '(nobreak-space ((((class color) (min-colors 89)) (:background "#CCE8F6"))))
 '(nxml-attribute-local-name-face ((((class color) (min-colors 89)) (:foreground "magenta"))))
 '(nxml-attribute-value-delimiter-face ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(nxml-attribute-value-face ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(nxml-comment-content-face ((((class color) (min-colors 89)) (:slant italic :foreground "red"))))
 '(nxml-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(nxml-element-local-name ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#999999") :foreground "#000088" :background "#DEDEDE"))))
 '(nxml-element-local-name-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(nxml-processing-instruction-target-face ((((class color) (min-colors 89)) (:foreground "purple1"))))
 '(nxml-tag-delimiter-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(nxml-tag-slash-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(org-archived ((((class color) (min-colors 89)) (:foreground "gray70"))))
 '(org-beamer-tag ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#FABC18") :foreground "#2C2C2C" :background "#FFF8D0"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#B8B8B8" :background "#003542"))))
 '(org-block-background ((((class color) (min-colors 89)) (:background "#FFFFE0"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:overline "#A7A6AA" :foreground "#555555" :background "#022b36"))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:extend t :underline "#A7A6AA" :foreground "#555555" :background "#022b36"))))
 '(org-checkbox ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :style pressed-button) :foreground "white" :background "#777777"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:foreground "white" :background "SkyBlue4"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#006400" :background "#FDFFF7"))))
 '(org-column ((((class color) (min-colors 89)) (:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "#E6AD4F" :background "#FFF2DE"))))
 '(org-column-title ((((class color) (min-colors 89)) (:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "#E6AD4F" :background "#FFF2DE"))))
 '(org-date ((((class color) (min-colors 89)) (:underline t :foreground "#00459E"))))
 '(org-default ((((class color) (min-colors 89)) (:foreground "#333333" :background "#FFFFFF"))))
 '(org-dim ((((class color) (min-colors 89)) (:foreground "#AAAAAA"))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "brown"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:inherit shadow :slant italic))))
 '(org-document-title ((((class color) (min-colors 89)) (:family "Sans Serif" :weight bold :foreground "black"))))
 '(org-done ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#BBBBBB") :foreground "#BBBBBB" :background "#F0F0F0"))))
 '(org-drawer ((((class color) (min-colors 89)) (:foreground "light sky blue"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:underline nil :box (:line-width 1 :color "#999999") :foreground "#999999" :background "#FFF8C0"))))
 '(org-example ((((class color) (min-colors 89)) (:foreground "blue" :background "#EAFFEA"))))
 '(org-footnote ((((class color) (min-colors 89)) (:underline t :foreground "#008ED1"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "chocolate1"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:height 1.0 :weight normal :strike-through t :foreground "#ADADAD"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#E2E2E2"))))
 '(org-inlinetask ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#EBEBEB") :foreground "#777777" :background "#FFFFD6"))))
 '(org-latex-and-related ((((class color) (min-colors 89)) (:foreground "#336699" :background "white"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(org-level-2 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#EA6300"))))
 '(org-level-5 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#E3258D"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#0077CC"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#2EAE2C"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#FD8008"))))
 '(org-link ((((class color) (min-colors 89)) (:weight normal :foreground "#04cca7"))))
 '(org-list-dt ((((class color) (min-colors 89)) (:weight bold :foreground "#335EA8"))))
 '(org-macro ((((class color) (min-colors 89)) (:foreground "white" :background "#EDB802"))))
 '(org-meta-line ((((class color) (min-colors 89)) (:slant normal :foreground "#797a7a"))))
 '(org-mode-line-clock ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#335EA8") :foreground "black" :background "#EEC900"))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#335EA8") :foreground "white" :background "#FF4040"))))
 '(org-number-of-items ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "#79BA79"))))
 '(org-property-value ((((class color) (min-colors 89)) (:foreground "#00A000"))))
 '(org-quote ((((class color) (min-colors 89)) (:slant italic :foreground "dim gray" :background "#FFFFE0"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#333333"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#F22659"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:weight bold :foreground "#4F4A3D" :background "#FFFFCC"))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#3774CC"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:weight bold :foreground "#00BB00" :background "#EAFFEA"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "dark green" :background "#EAFFEA"))))
 '(org-tag ((((class color) (min-colors 89)) (:weight normal :slant italic :foreground "#9A9FA4" :background "white"))))
 '(org-target ((((class color) (min-colors 89)) (:weight normal :foreground "#04cca7"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#CFCFCF"))))
 '(org-todo ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#D8ABA7") :foreground "#D8ABA7" :background "#FFE6E4"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#FF5555"))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#0066CC"))))
 '(org-verse ((((class color) (min-colors 89)) (:slant italic :foreground "dim gray" :background "#EEEEEE"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#CCE7FF"))))
 '(outline-1 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(outline-2 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))))
 '(outline-3 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF"))))
 '(outline-4 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#EA6300"))))
 '(outline-5 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#E3258D"))))
 '(outline-6 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#0077CC"))))
 '(outline-7 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#2EAE2C"))))
 '(outline-8 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#FD8008"))))
 '(pabbrev-debug-display-label-face ((((class color) (min-colors 89)) (:background "chartreuse"))))
 '(pabbrev-suggestions-face ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "red"))))
 '(pabbrev-suggestions-label-face ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "purple"))))
 '(paren-face-match ((((class color) (min-colors 89)) (:background "#3e3b32" :foreground "white"))))
 '(paren-face-mismatch ((((class color) (min-colors 89)) (:underline "red" :background "navy" :foreground "white"))))
 '(paren-face-no-match ((((class color) (min-colors 89)) (:underline "red" :background "navy" :foreground "white"))))
 '(persp-selected-face ((((class color) (min-colors 89)) (:weight bold :foreground "#EEF5FE"))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:background "grey22" :inherit mode-line))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:background "#4070B6" :inherit mode-line))))
 '(powerline-inactive1 ((((class color) (min-colors 89)) (:background "#686868" :inherit mode-line-inactive))))
 '(powerline-inactive2 ((((class color) (min-colors 89)) (:background "#A9A9A9" :inherit mode-line-inactive))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#707183"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#7388D6"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#909183"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#709870"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#907373"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#6276BA"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#858580"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#80A880"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#887070"))))
 '(rainbow-delimiters-mismatched-face ((((class color) (min-colors 89)) (:underline "red" :background "navy" :foreground "white"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:underline "red" :background "navy" :foreground "white"))))
 '(realgud-backtrace-number ((((class color) (min-colors 89)) :foreground "#A535AE" :weight bold)))
 '(realgud-bp-disabled-face ((((class color) (min-colors 89)) (:foreground "#909183"))))
 '(realgud-bp-line-disabled-face ((((class color) (min-colors 89)) (:underline "#909183"))))
 '(realgud-bp-line-enabled-face ((((class color) (min-colors 89)) (:underline "red"))))
 '(realgud-file-name ((((class color) (min-colors 89)) :foreground "#005522")))
 '(realgud-line-number ((((class color) (min-colors 89)) :foreground "#A535AE")))
 '(realgud-overlay-arrow1 ((((class color) (min-colors 89)) (:foreground "#005522"))))
 '(realgud-overlay-arrow2 ((((class color) (min-colors 89)) (:foreground "#c18401"))))
 '(realgud-overlay-arrow3 ((((class color) (min-colors 89)) (:foreground "#909183"))))
 '(recover-this-file ((((class color) (min-colors 89)) (:weight bold :background "#FF3F3F"))))
 '(region ((((class color) (min-colors 89)) (:bold t :background "#556832" :foreground "white"))))
 '(rng-error ((((class color) (min-colors 89)) (:weight bold :foreground "red" :background "#FBE3E4"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:weight bold :background "#1f1f1f"))))
 '(sh-heredoc ((((class color) (min-colors 89)) (:foreground "blue" :background "#EEF5FE"))))
 '(sh-quoted-exec ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#7F7F7F"))))
 '(shell-option-face ((((class color) (min-colors 89)) (:foreground "forest green"))))
 '(shell-output-2-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(shell-output-3-face ((((class color) (min-colors 89)) (:foreground "purple"))))
 '(shell-output-face ((((class color) (min-colors 89)) (:foreground "black"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#3e3b32" :foreground "white"))))
 '(show-paren-match-expression ((t (:background "#021f26" :foreground nil))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:underline "red" :background "navy" :foreground "white"))))
 '(smerge-refined-change ((((class color) (min-colors 89)) (:background "#AAAAFF"))))
 '(sml-modeline-end-face ((((class color) (min-colors 89)) (:background "#6BADF6"))))
 '(sml-modeline-vis-face ((((class color) (min-colors 89)) (:background "#1979CA"))))
 '(speedbar-button-face ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(speedbar-directory-face ((((class color) (min-colors 89)) (:foreground "blue4"))))
 '(speedbar-file-face ((((class color) (min-colors 89)) (:foreground "cyan4"))))
 '(speedbar-highlight-face ((((class color) (min-colors 89)) (:underline nil :background "#586e75" :foreground "#002b36"))))
 '(speedbar-selected-face ((((class color) (min-colors 89)) (:underline t :foreground "red"))))
 '(speedbar-tag-face ((((class color) (min-colors 89)) (:foreground "brown"))))
 '(success ((((class color) (min-colors 89)) (:foreground "green"))))
 '(svn-status-directory-face ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(svn-status-filename-face ((((class color) (min-colors 89)) (:weight bold :foreground "#4183C4"))))
 '(svn-status-locked-face ((((class color) (min-colors 89)) (:weight bold :foreground "red"))))
 '(svn-status-marked-face ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "red"))))
 '(svn-status-marked-popup-face ((((class color) (min-colors 89)) (:weight bold :foreground "green3"))))
 '(svn-status-switched-face ((((class color) (min-colors 89)) (:slant italic :foreground "gray55"))))
 '(svn-status-symlink-face ((((class color) (min-colors 89)) (:foreground "deep sky blue"))))
 '(svn-status-update-available-face ((((class color) (min-colors 89)) (:foreground "orange"))))
 '(tex-verbatim ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(tool-bar ((((class color) (min-colors 89)) (:box (:line-width 1 :style released-button) :foreground "black" :background "gray75"))))
 '(tooltip ((((class color) (min-colors 89)) (:foreground "black" :background "light yellow"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#FFFF57"))))
 '(traverse-match-face ((((class color) (min-colors 89)) (:weight bold :foreground "blue violet"))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(vc-annotate-face-3F3FFF ((((class color) (min-colors 89)) (:foreground "#3F3FFF" :background "black"))))
 '(vc-annotate-face-3F6CFF ((((class color) (min-colors 89)) (:foreground "#3F3FFF" :background "black"))))
 '(vc-annotate-face-3F99FF ((((class color) (min-colors 89)) (:foreground "#3F99FF" :background "black"))))
 '(vc-annotate-face-3FC6FF ((((class color) (min-colors 89)) (:foreground "#3F99FF" :background "black"))))
 '(vc-annotate-face-3FF3FF ((((class color) (min-colors 89)) (:foreground "#3FF3FF" :background "black"))))
 '(vc-annotate-face-3FFF56 ((((class color) (min-colors 89)) (:foreground "#4BFF4B" :background "black"))))
 '(vc-annotate-face-3FFF83 ((((class color) (min-colors 89)) (:foreground "#3FFFB0" :background "black"))))
 '(vc-annotate-face-3FFFB0 ((((class color) (min-colors 89)) (:foreground "#3FFFB0" :background "black"))))
 '(vc-annotate-face-3FFFDD ((((class color) (min-colors 89)) (:foreground "#3FF3FF" :background "black"))))
 '(vc-annotate-face-56FF3F ((((class color) (min-colors 89)) (:foreground "#4BFF4B" :background "black"))))
 '(vc-annotate-face-83FF3F ((((class color) (min-colors 89)) (:foreground "#B0FF3F" :background "black"))))
 '(vc-annotate-face-B0FF3F ((((class color) (min-colors 89)) (:foreground "#B0FF3F" :background "black"))))
 '(vc-annotate-face-DDFF3F ((((class color) (min-colors 89)) (:foreground "#FFF33F" :background "black"))))
 '(vc-annotate-face-FF3F3F ((((class color) (min-colors 89)) (:foreground "#FF3F3F" :background "black"))))
 '(vc-annotate-face-FF6C3F ((((class color) (min-colors 89)) (:foreground "#FF3F3F" :background "black"))))
 '(vc-annotate-face-FF993F ((((class color) (min-colors 89)) (:foreground "#FF993F" :background "black"))))
 '(vc-annotate-face-FFC63F ((((class color) (min-colors 89)) (:foreground "#FF993F" :background "black"))))
 '(vc-annotate-face-FFF33F ((((class color) (min-colors 89)) (:foreground "#FFF33F" :background "black"))))
 '(vimish-fold-overlay ((t (:foreground "white" :background "#02404f"))))
 '(w3m-anchor ((((class color) (min-colors 89)) (:weight normal :foreground "#04cca7"))))
 '(w3m-arrived-anchor ((((class color) (min-colors 89)) (:foreground "purple1"))))
 '(w3m-bitmap-image-face ((((class color) (min-colors 89)) (:foreground "gray4" :background "green"))))
 '(w3m-bold ((((class color) (min-colors 89)) (:weight bold :foreground "black"))))
 '(w3m-current-anchor ((((class color) (min-colors 89)) (:weight bold :underline t :foreground "blue"))))
 '(w3m-form ((((class color) (min-colors 89)) (:underline t :foreground "tan1"))))
 '(w3m-form-button-face ((((class color) (min-colors 89)) (:weight bold :underline t :foreground "gray4" :background "light grey"))))
 '(w3m-form-button-mouse-face ((((class color) (min-colors 89)) (:underline t :foreground "light grey" :background "#2B7E2A"))))
 '(w3m-form-button-pressed-face ((((class color) (min-colors 89)) (:weight bold :underline t :foreground "gray4" :background "light grey"))))
 '(w3m-header-line-location-content-face ((((class color) (min-colors 89)) (:foreground "#7F7F7F" :background "#F7F7F7"))))
 '(w3m-header-line-location-title-face ((((class color) (min-colors 89)) (:foreground "#2C55B1" :background "#F7F7F7"))))
 '(w3m-history-current-url-face ((((class color) (min-colors 89)) (:foreground "lemon chiffon"))))
 '(w3m-image-face ((((class color) (min-colors 89)) (:weight bold :foreground "DarkSeaGreen2"))))
 '(w3m-link-numbering ((((class color) (min-colors 89)) (:foreground "#B4C7EB"))))
 '(w3m-strike-through-face ((((class color) (min-colors 89)) (:strike-through t))))
 '(w3m-underline-face ((((class color) (min-colors 89)) (:underline t))))
 '(warning ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(which-func ((((class color) (min-colors 89)) (:weight bold :foreground "white"))))
 '(which-key-command-description-face ((t (:inherit default))))
 '(which-key-group-description-face ((t (:inherit default :foreground "yellow" :weight bold))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:foreground "#D2D2D2"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:foreground "#A1A1A1" :background "white"))))
 '(whitespace-line ((((class color) (min-colors 89)) (:foreground "#CC0000" :background "#FFFF88"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:foreground "#A1A1A1" :background "white"))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:foreground "#B3B3B3" :background "#FFFF57"))))
 '(widget-button ((((class color) (min-colors 89)) (:weight normal :foreground "#04cca7"))))
 '(widget-button-pressed ((((class color) (min-colors 89)) (:foreground "red"))))
 '(widget-documentation ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(widget-field ((((class color) (min-colors 89)) (:background "gray85"))))
 '(widget-inactive ((((class color) (min-colors 89)) (:foreground "dim gray"))))
 '(widget-single-line-field ((((class color) (min-colors 89)) (:background "gray85"))))
 '(yas/field-debug-face ((((class color) (min-colors 89)) (:background "ivory2"))))
 '(yas/field-highlight-face ((((class color) (min-colors 89)) (:background "DarkSeaGreen1")))))
