(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(anzu-deactivate-region t)
 '(anzu-mode-lighter " Az ")
 '(anzu-mode-line-update-function #'my/anzu-update-func)
 '(anzu-replace-threshold 50)
 '(anzu-replace-to-string-separator " => ")
 '(anzu-search-threshold 1000)
 '(custom-safe-themes
   '("28a104f642d09d3e5c62ce3464ea2c143b9130167282ea97ddcc3607b381823f" default))
 '(helm-ff-lynx-style-map t)
 '(helm-grep-use-ioccur-style-keys t)
 '(helm-imenu-lynx-style-map t)
 '(helm-occur-use-ioccur-style-keys t)
 '(helm-semantic-lynx-style-map t)
 '(sml/pos-id-separator "| ")
 '(sml/pos-minor-modes-separator " /")
 '(sml/pre-id-separator "|")
 '(sml/pre-minor-modes-separator "/ ")
 '(sml/pre-modes-separator "| |"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(comint-highlight-input ((t (:foreground "#2aa198"))))
 '(comint-highlight-prompt ((((min-colors 88) (background dark)) (:foreground "#268bd2"))))
 '(company-preview-common ((t (:inherit company-preview :foreground "brightcyan"))))
 '(company-preview-search ((t (:inherit company-preview :background "black"))))
 '(company-scrollbar-bg ((t (:background "dark green"))))
 '(company-scrollbar-fg ((t (:background "red"))))
 '(company-template-field ((t (:background "black" :foreground "chartreuse"))))
 '(company-tooltip ((t (:background "black" :foreground "yellow green"))))
 '(company-tooltip-search ((t (:foreground "dark khaki" :underline "blue"))))
 '(company-tooltip-selection ((t (:background "honeydew" :foreground "dark green"))))
 '(helm-buffer-directory ((t (:foreground "LimeGreen"))))
 '(helm-buffer-file ((t (:foreground "White"))))
 '(helm-ff-denied ((t (:foreground "red" :background nil :weight bold))))
 '(helm-ff-directory ((t (:foreground "LimeGreen"))))
 '(helm-ff-dotted-directory ((t (:foreground "LimeGreen"))))
 '(helm-ff-dotted-symlink-directory ((((class color) (background dark)) :foreground "#8b0000")))
 '(helm-ff-file ((t (:foreground "gray75" :background nil))))
 '(helm-ff-invalid-symlink ((((class color) (background dark)) :foreground "black" :background "red")))
 '(helm-ff-prefix ((t (:foreground "red" :background nil :weight bold))))
 '(helm-ff-symlink ((t (:foreground "blue" :background "DarkOliveGreen"))))
 '(helm-grep-match ((t (:foreground "#511a1a"))))
 '(helm-match ((t (:foreground "#511a1a"))))
 '(helm-match-item ((t (:foreground "#511a1a" :weight bold))))
 '(helm-non-file-buffer ((t (:foreground "red"))))
 '(helm-selection ((t (:background "#575757" :weight bold))))
 '(helm-source-header ((t (:foreground "white" :background "#511a1a" :weight bold :height 150))))
 '(helm-swoop-line-number-face ((t (:foreground "GreenYellow"))))
 '(helm-visible-mark ((t (:foreground "black" :background "goldenrod"))))
 '(ivy-modified-buffer ((t (:inherit default :weight bold :foreground "#FD971F"))))
 '(ivy-modified-outside-buffer ((t (:foreground "red" :weight bold))))
 '(ivy-virtual ((t (:inherit default :foreground "green"))))
 '(vimish-fold-overlay ((t (:foreground "white" :background "#02404f"))))
 '(which-key-command-description-face ((t (:inherit default))))
 '(which-key-group-description-face ((t (:inherit default :foreground "yellow" :weight bold)))))
