# -*- mode: org; -*-
#+TITLE: README
#+DESCRIPTION:
#+KEYWORDS: emacs
#+AUTHOR:
#+email:
#+INFOJS_OPT:
#+STARTUP:  content

#+DATE: CREATED: <Wed Jul 28 20:20:51 EEST 2021>
# Time-stamp: <Последнее обновление -- Sunday February 5 22:3:10 MSK 2023>


* Это мои настройки для ~emacs~.

  В ~emacs~ бесконечное множество команд и сочетаний клавиш (~keybindings~) для работы с ними.
  Копаться и разбираться в них та ещё задача! Но по прошествии определённого промежутка времени
  начинаешь понимать, что, в принципе, всё не так уж и сложно.

  Здесь я постарался описать *свои* настройки, сочетания клавиш, а также некоторые переопределения оных
  в связи со своими предпочтениями.

  В директории ~.emacs.d~ есть подкаталог ~.emacs.d/emacs_help/~, в котором расположена некоторая
  справочная информация, которую я счёл нецелесообразным располагать на этой странице, ссылки
  оформлены в виде обычного содержания и расположены в конце этого файла.

** Установка

   - клонируйте этот репозиторий:

   #+begin_src shell

   git clone https://github.com/abunbux/emacs-config.git ~/.emacs.d

   #+end_src

** Пояснения по структуре каталогов

   - если настройки не расположены в файле ~init.el~, значит они в директории ~.emacs.d/custom/~,
     именование файлов говорит само за себя.
   - в директории ~.emacs.d/custom/not_connected/~ расположены файлы конфигурации, в данный момент не
     используемые, но возможно ещё пригодятся (да, я Плюшкин).
   - в директории ~.emacs.d/lisp~ файлы с модами ~emacs~, которые клонировать смысла нет в силу того, что
     они уже давно не поддерживаются, но своей актуальности, по крайней мере для меня, не утратили. Я
     их просто скопировал.
   - название ~.emacs.d/cache/~ в пояснении, думаю, не нуждается, подробности читаем ниже.
   - каталог ~.emacs.d/elpa/~ создаётся автоматически при установке пакетов (модов) с помощью [[https://github.com/emacs-mirror/emacs/blob/master/lisp/emacs-lisp/package.el][package.el]].
   - некоторые пакеты отсутствуют в официальных репозиториях (melpa, gnu и т.д.), есть различные
     способы их установки, я же использую [[https://github.com/quelpa/quelpa][quelpa]], которая создаёт каталог ~.emacs.d/quelpa~.
   - ~.emacs.d/snippets/~ содержит сниппеты для [[https://github.com/joaotavora/yasnippet][yasnippet]].
   - ~.emacs.d/templates-autoinsert/~ шаблоны для [[https://github.com/emacs-mirror/emacs/blob/master/lisp/autoinsert.el][auto-insert]].
   - ~.emacs.d/themes/~ конфигурации для настроек внешнего вида.

** Ещё кое-что

   Я являюсь сторонником использования [[https://github.com/jwiegley/use-package][use-package]].

   Переменную ~use-package-always-ensure~ в ~t~ не устанавливал, поэтому после первого запуска ~emacs~ будет
   загружать необходимые пакеты, остальная часть будет загружена при первом использовании - например
   ~visual-regexp (vr/)~.

   PS. (~setq use-package-always-ensure t~) говорит ~use-package~ при отсутсвии пакета установить его ещё
   во время инициализации ~emacs~. Если же эта переменная установлена в ~nil~, то пакет будет установлен
   только в момент первого обращения к нему.

** Некоторые ссылки

   О дефолтных командах и биндингах можно прочитать по следующим ссылкам:
   - [[https://caiorss.github.io/Emacs-Elisp-Programming/Keybindings.html][Emacs Key Bindings]] (мануал от [[https://github.com/caiorss][caiorss]]).
   - [[https://www.gnu.org/software/emacs/refcards/pdf/refcard.pdf][GNU Emacs Reference Card (for version 28)]] (внешняя ссылка на pdf файл).

   либо ищем на просторах Всезнающей Сети.


[[file:emacs_help/index.org][Небольшая справочная система для моей памяти]]
