(deftheme poet
  "Created 2021-07-29.")

(custom-theme-set-variables
 'poet
 '(line-spacing 0.2))

(custom-theme-set-faces
 'poet
 '(variable-pitch ((t (:family "IBM Plex Serif" :height (lambda (_x) (poet-theme--height 1))))))
 '(italic ((t (:foreground "#222222" :slant italic))))
 '(highlight ((t (:background "#efefef" :overline nil))))
 '(region ((t (:background "#fff8e1"))))
 '(fringe ((t (:background "#e1d9c2"))))
 '(button ((t (:inherit default :foreground "#616161"))))
 '(escape-glyph ((t (:foreground "#673AB7"))))
 '(link ((t (:underline (:color "#304ffe" :style line) :foreground "#303f9f"))))
 '(link-visited ((t (:inherit link :foreground "#303f9f" :underline (:color "#1a237e" :style line)))))
 '(cursor ((t (:background "#333333"))))
 '(show-paren-match ((t (:background "#ffffff" :foreground "#ff1744"))))
 '(isearch ((t (:foreground "#c2185b" :background "#ffffff"))))
 '(isearch-fail ((t (:background "#f8bbd0"))))
 '(query-replace ((t (:inherit isearch))))
 '(tooltip ((t (:inherit default :foreground "#111111" :background "#fff176"))))
 '(shadow ((t (:foreground "#999999"))))
 '(secondary-selection ((t (:background "#fff59d"))))
 '(trailing-whitespace ((t (:background "#ff8a65"))))
 '(lazy-highlight ((t (:foreground "#000000" :background "#ffffff"))))
 '(next-error ((t (:inherit region))))
 '(window-divider ((t (:background "#eeeeee" :foreground "#eeeeee"))))
 '(vertical-border ((t (:background "#eeeeee" :foreground "#eeeeee"))))
 '(minibuffer-prompt ((t (:inherit fixed-pitch :weight bold :foreground "#4e342e"))))
 '(mode-line ((t (:inherit fixed-pitch :foreground "#111111" :background "#e1d9c2" :overline "#eeeeee" :box (:line-width 3 :color "#e1d9c2")))))
 '(header-line ((t (:overline nil :background "#e0e0e0" :box (:line-width 3 :color "#e0e0e0") :underline "#eeeeee" :inherit mode-line))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:background "#ffffff"))))
 '(mode-line-inactive ((t (:inherit mode-line :background "#e1d9c2" :foreground "#888888" :box (:color "#e1d9c2" :line-width 3)))))
 '(error ((t (:foreground "#df5286" :inherit fixed-pitch))))
 '(font-lock-comment-face ((t (:foreground "#795548" :inherit fixed-pitch))))
 '(font-lock-builtin-face ((t (:foreground "#795548" :inherit fixed-pitch))))
 '(font-lock-string-face ((t (:inherit fixed-pitch :foreground "#6C3082"))))
 '(font-lock-function-name-face ((t (:inherit fixed-pitch :foreground "#388E3C"))))
 '(font-lock-keyword-face ((t (:inherit fixed-pitch :foreground "#bf360c"))))
 '(font-lock-comment-delimiter-face ((t (:inherit fixed-pitch :inherit font-lock-comment-face))))
 '(font-lock-constant-face ((t (:inherit fixed-pitch :foreground "#0288D1"))))
 '(font-lock-doc-face ((t (:inherit fixed-pitch :inherit font-lock-string-face))))
 '(font-lock-preprocessor-face ((t (:inherit fixed-pitch :inherit font-lock-builtin-face))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit fixed-pitch :inherit bold))))
 '(font-lock-regexp-grouping-construct ((t (:inherit fixed-pitch :inherit bold))))
 '(font-lock-type-face ((t (:foreground "#3f51b5" :inherit fixed-pitch))))
 '(font-lock-variable-name-face ((t (:inherit fixed-pitch :foreground "#455A64"))))
 '(font-lock-warning-face ((t (:inherit error))))
 '(hl-line ((t (:background "#efefef"))))
 '(line-number ((t (:inherit fixed-pitch :foreground "#aaaaaa"))))
 '(line-number-current-line ((t (:inherit fixed-pitch :foreground "#555555"))))
 '(helm-source-header ((t (:height (lambda (_x) (poet-theme--height 1))))))
 '(ivy-org ((t (:inherit fixed-pitch))))
 '(default ((t (:background "#e1d9c2" :foreground "#444444")))))

(provide-theme 'poet)
